 // eslint-disable-next-line no-unused-expressions
 [{ batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",             majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
        { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},
        { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "专业平行志愿批", batchDisplayName: "专业平行志愿批", volunteerDisplayName: "三志愿", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},


       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
        { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科提前批（B段）", batchDisplayName: "本科提前批（B段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "一志愿", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
        { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科提前批（C段）", batchDisplayName: "本科提前批（C段）", volunteerDisplayName: "二志愿", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},


       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科一批", batchDisplayName: "本科一批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},   
       
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿A", volunteerSortNo: 0, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿B", volunteerSortNo: 1, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿C", volunteerSortNo: 2, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿D", volunteerSortNo: 3, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿E", volunteerSortNo: 4, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5},

       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业1",majorSortNo:0},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业2",majorSortNo:1},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业3",majorSortNo:2},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业4",majorSortNo:3},
        { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业5",majorSortNo:4},
       { batchName: "本科二批", batchDisplayName: "本科二批", volunteerDisplayName: "平行志愿F", volunteerSortNo: 5, collegeID:"", collegeName:"待选院校",majorID:"",majorName:"待选专业6",majorSortNo:5}  
      
      ]